services:
  - type: web
    name: host-elite-bot-platform
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: host-elite-storage
      mountPath: /opt/render/project/src/deployed_bots
      sizeGB: 1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
