services:
  - type: web
    name: host-elite-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
    healthCheckPath: /api/health
    disk:
      name: host-elite-disk
      mountPath: /tmp
      sizeGB: 1
