services:
  - type: web
    name: host-elite-bot-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production=false
    startCommand: node server/production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true
    healthCheckPath: /api/health
    disk:
      name: host-elite-disk
      mountPath: /tmp
      sizeGB: 1
