services:
  - type: web
    name: host-elite-bot-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci --only=production && npm install vite@latest esbuild@latest --save-dev && npx vite build --config vite.config.ts && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true
    healthCheckPath: /api/health
    disk:
      name: host-elite-disk
      mountPath: /tmp
      sizeGB: 1
