services:
  - type: web
    name: host-elite-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_OPTIONS
        value: --max-old-space-size=1024
    healthCheckPath: /api/health
    disk:
      name: host-elite-disk
      mountPath: /tmp
      sizeGB: 1
