services:
  - type: web
    name: host-elite-bot-platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production=false && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=cjs --outdir=dist
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true
    healthCheckPath: /api/health
    disk:
      name: host-elite-disk
      mountPath: /tmp
      sizeGB: 1
