services:
  - type: web
    name: host-elite-bot-platform
    env: node
    plan: free
    buildCommand: npm ci --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: PORT
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "node_modules/**"
        - ".git/**"
        - "*.log"
    disk:
      name: host-elite-storage
      mountPath: /opt/render/project/src/deployed_bots
      sizeGB: 1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
